[package]
name = "droprabbit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = { version = "23", default-features = false, features = ["minimal", "rustls-tls"] }
